### ISSUE TITLE
Allow only Bangazonians access to the API

### ISSUE THREAD

**Issue by stevebrownlee** [Abcrete/BangazonAPI#12]
Update, and use, a CORS policy that only allows requests from the `http://bangazon.com` domain.

Ref: https://docs.microsoft.com/en-us/aspnet/core/security/cors

**Comment by jordandhaenens** [comment]
Not everyone has enabled CORS on their controllers

**Comment by tlerma83** [comment]
enabled Cors on Computer ad Employee Controller

**Comment by ghost** [comment]
enabled Cors on Computer ad Employee Controller #47 #58
